### ISSUE TITLE
ロウソクのクオリティを上げたい

### ISSUE THREAD

**Issue by shotay79** [publika/HackableBar#10]

**Comment by wktq** [comment]
カメヤマローソクは面倒だったので、LEDのローソクライトみたいなのを買おうと思うんですがどうでしょう？？

https://www.amazon.co.jp/gp/product/B07GZBTRJ3/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by shotay79** [comment]
@wktq
